---
  parser: "babel-eslint"
  plugins:
  - react
  rules:
    arrow-parens: 0
    comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: ignore
    func-names:
    - error
    - as-needed
    function-paren-newline:
    - error
    - consistent
    max-len:
    - warn
    - code: 120
      ignoreUrls: true
      ignoreRegExpLiterals: true
    no-else-return: 0
    no-return-assign:
    - error
    - except-parens
    no-underscore-dangle: 0
    no-unused-expressions:
    - error
    - allowTernary: true
      allowShortCircuit: true
    object-curly-newline:
    - warn
    - consistent: true
    operator-linebreak: 0
    semi: 0
    react/boolean-prop-naming:
    - error
    react/button-has-type:
    - error
    react/default-props-match-prop-types:
    - error
    react/no-array-index-key:
    - error
    react/no-danger:
    - error
    react/no-did-mount-set-state:
    - error
    react/no-did-update-set-state:
    - error
    react/no-typos:
    - error
    react/no-unsafe:
    - error
    react/no-unused-prop-types:
    - warn
    react/no-unused-state:
    - error
    react/jsx-child-element-spacing:
    - warn
    react/jsx-closing-bracket-location:
    - error
    react/jsx-curly-spacing:
    - error
    react/jsx-equals-spacing:
    - error
    react/jsx-indent:
    - error
    - 2
    react/jsx-handler-names:
    - error
    react/jsx-no-bind:
    - error
    react/jsx-pascal-case:
    - error
    react/jsx-props-no-multi-spaces:
    - error
    react/jsx-tag-spacing:
    - error
    react/jsx-wrap-multilines:
    - error
  globals:
    alert: true
    document: true
    window: true
    HTMLElement: true
    ReactRailsUJS: true
  settings:
    react:
      version: "16.8"
    import/resolver:
      node:
        moduleDirectory:
        - node_modules
        - app/javascript
  extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "airbnb-base"
