version: 2
jobs:
  test:
    working_directory: ~/release_maker
    docker:
      - image: randomservices/ruby:2.6.1
        environment:
          DATABASE_URL: postgresql://ubuntu@localhost/release_maker_test?sslmode=disable
          RAILS_ENV: test
          RACK_ENV: test
      - image: postgres:10.1
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: release_maker_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          keys:
          - release_maker-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          - release_maker-master-{{ checksum "Gemfile.lock" }}
      - run:
          name: bundle install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: release_maker-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - "~/release_maker/vendor/bundle"
      - run:
          name: set up database
          command: bundle exec rake db:create db:schema:load --trace
      - run:
          name: results folder
          command: mkdir /tmp/test-reports
      - run:
          name: Webpack Build
          command: bin/webpack
      - run:
          name: rspec
          command: bundle exec rspec --color --require rails_helper --format RspecJunitFormatter --out /tmp/test-reports/rspec.xml spec --format doc
      - store_artifacts:
          path: /tmp/artifacts
          destination: build
      - store_test_results:
          path: /tmp/test-reports
  deploy-to-staging:
    working_directory: ~/release_maker
    docker:
      - image: randomservices/ruby:2.6.1
        environment:
          RAILS_ENV: test
          RACK_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
          - release_maker-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          - release_maker-master-{{ checksum "Gemfile.lock" }}
      - run:
          name: bundle install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run:
          name: add host SSH keys
          command: 'echo "hazel.rndsvc.net,18.217.125.199 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNKmVLo32LqgAgWvUJD681vB34qITMKWnjoX2uxXLwRliC+6xh0g5TLz8PJxU0X0R2nTaOrcusNJMLCRpiYrot8=" >> ~/.ssh/known_hosts'
      - run:
          name: deploy
          command: bundle exec cap staging deploy
  deploy-to-production:
    working_directory: ~/release_maker
    docker:
      - image: randomservices/ruby:2.6.1
        environment:
          RAILS_ENV: test
          RACK_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
          - release_maker-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          - release_maker-master-{{ checksum "Gemfile.lock" }}
      - run:
          name: bundle install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run:
          name: add host SSH keys
          command: 'echo "hazel.rndsvc.net,18.217.125.199 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNKmVLo32LqgAgWvUJD681vB34qITMKWnjoX2uxXLwRliC+6xh0g5TLz8PJxU0X0R2nTaOrcusNJMLCRpiYrot8=" >> ~/.ssh/known_hosts'
      - run:
          name: deploy
          command: bundle exec cap production deploy
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: '/^v[0-9]+\.[0-9]+\.[0-9]+$/'
      - deploy-to-staging:
          filters:
            branches:
              only:
                - master
            tags:
              ignore: /.*/
          requires:
            - test
      - deploy-to-production:
          filters:
            tags:
              only: '/^v[0-9]+\.[0-9]+\.[0-9]+$/'
            branches:
              ignore: /.*/
          requires:
            - test
