default: &default
  oauth_client_id: <%= ENV['GITHUB_OAUTH_CLIENT_ID'] %>
  oauth_secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
  webhook_secret: <%= ENV['GITHUB_WEBHOOK_SECRET'] %>

development:
  <<: *default

test:
  <<: *default
  test_repo_name: RobinDaugherty/release-maker-tester-no-releases
  test_repo_uid: 104763724
  test_auth_token: <%= ENV['GITHUB_AUTH_TOKEN'] %>

staging:
  <<: *default

production:
  <<: *default
